name: Artifact-Demo-Task4

on:
    push:
        branches: [main]


jobs:
    artifact_create_and_demo:
        runs-on: ubuntu-latest
        steps:
            - name: Generate Test Report
              run: |
                mkdir -p reports
                echo "Test Execution Started" > reports/test-report.txt
                echo "All test passed" >> reports/test-report.txt
                echo "Build time: $(date)" >> reports/test-report.txt

            - name: Upload Test Report Artifact
              uses: actions/upload-artifact@v4
              with:
                name : test-report
                path: reports/test-report.txt    

    dowload_artifact:
        runs-on: ubuntu-latest
        steps:
            - name: Download Single arifact from Job1
              uses: actions/download-artifact@v5
              with:
                name: test-report
