name: Cache-Demo

on:
    push:
        branches: [main]

jobs:
    cache_demo:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"
            - name: Cache pip dependencies
              uses: actions/cache@v4
              with:
                path: ~/.cache/pip
                key: pip-cache-${{ hashFiles('requirements.txt') }}

            - name: Install Dependencies for require
              run: |
               pip install -r requirements.txt    