name: Ignore Path

on:
    push:
       branches:
            - main
            - 'release/*'
       paths-ignore:
         - '*.md'
         - 'docs/**'

jobs:
    ignore-path:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Print Message
              run: echo "skip runs only if any changes in .md or doc"