name: Real_test_CI

on:
    push:
        branches: [main]

jobs:
    real_test_CI:
        runs-on: ubuntu-latest
        steps:
            - name: Check Out Code
              uses: actions/checkout@v4

            - name: Give Permission to sh file
              run: chmod +x test-script.sh       
              
            - name: Run Shell Script
              run: ./test-script.sh
